Repository NOW-SOPT-APP3-PlanFit/PlanFit-SERVER, pull requests merged in 2024-05, with the labels that each got.

#2 [FEAT] 프로젝트 셋업(#1)
  planfit/.gitignore
  planfit/build.gradle
  planfit/gradle/wrapper/gradle-wrapper.jar
  planfit/gradle/wrapper/gradle-wrapper.properties
  planfit/gradlew
  planfit/gradlew.bat
  planfit/settings.gradle
  planfit/src/main/java/com/planfit/server/PlanfitApplication.java
  planfit/src/test/java/com/planfit/server/PlanfitApplicationTests.java
Labels: enhancement

#5 [SETTING] BaseResponse 세팅(#3)
  planfit/src/main/java/com/planfit/server/common/ApiResponseUtil.java
  planfit/src/main/java/com/planfit/server/common/BaseResponse.java
  planfit/src/main/java/com/planfit/server/common/message/ErrorMessage.java
  planfit/src/main/java/com/planfit/server/common/message/SuccessMessage.java
Labels: 🦦성준, ⚙️ Settings

#6 [FEAT] JPA 엔티티 정의(#4)
  planfit/.gitignore
  planfit/src/main/java/com/planfit/server/domain/Exercise.java
  planfit/src/main/java/com/planfit/server/domain/Routine.java
  planfit/src/main/java/com/planfit/server/domain/Set.java
  planfit/src/main/java/com/planfit/server/domain/User.java
Labels: 🎸건우, ✨ Feat

#10 [FEAT] 운동 리스트 조회 API 구현 (#9)
  planfit/src/main/java/com/planfit/server/common/exception/BadRequestException.java
  planfit/src/main/java/com/planfit/server/common/exception/PlanfitException.java
  planfit/src/main/java/com/planfit/server/common/handler/GlobalExceptionHandler.java
  planfit/src/main/java/com/planfit/server/common/message/ErrorMessage.java
  planfit/src/main/java/com/planfit/server/common/message/SuccessMessage.java
  planfit/src/main/java/com/planfit/server/controller/ExerciseController.java
  planfit/src/main/java/com/planfit/server/domain/Exercise.java
  planfit/src/main/java/com/planfit/server/domain/Routine.java
  planfit/src/main/java/com/planfit/server/dto/response/ExerciseGetAllResponse.java
  planfit/src/main/java/com/planfit/server/dto/response/ExerciseGetResponse.java
  planfit/src/main/java/com/planfit/server/repository/ExerciseRepository.java
  planfit/src/main/java/com/planfit/server/repository/RoutineRepository.java
  planfit/src/main/java/com/planfit/server/repository/UserRepository.java
  planfit/src/main/java/com/planfit/server/service/ExerciseService.java
Labels: ✨ Feat, 🐶채원

#11 [FEAT] 운동 좋아요(하트) 활성화/비활성화 API 구현 (#8)
  planfit/build.gradle
  planfit/src/main/java/com/planfit/server/common/BaseResponse.java
  planfit/src/main/java/com/planfit/server/common/message/ErrorMessage.java
  planfit/src/main/java/com/planfit/server/common/message/SuccessMessage.java
  planfit/src/main/java/com/planfit/server/controller/RoutineController.java
  planfit/src/main/java/com/planfit/server/domain/Routine.java
  planfit/src/main/java/com/planfit/server/repository/ExerciseRepository.java
  planfit/src/main/java/com/planfit/server/repository/RoutineRepository.java
  planfit/src/main/java/com/planfit/server/service/RoutineService.java
Labels: 🦦성준, ✨ Feat

#12 [FEAT] 회원(홈 화면) 조회, 수정 API 구현(#7)
  planfit/src/main/java/com/planfit/server/common/exception/NotFoundException.java
  planfit/src/main/java/com/planfit/server/common/handler/GlobalExceptionHandler.java
  planfit/src/main/java/com/planfit/server/common/message/ErrorMessage.java
  planfit/src/main/java/com/planfit/server/common/message/SuccessMessage.java
  planfit/src/main/java/com/planfit/server/controller/UserController.java
  planfit/src/main/java/com/planfit/server/domain/User.java
  planfit/src/main/java/com/planfit/server/dto/request/UserPutRequest.java
  planfit/src/main/java/com/planfit/server/dto/response/UserGetResponse.java
  planfit/src/main/java/com/planfit/server/service/UserService.java
  planfit/src/test/java/com/planfit/server/service/UserServiceTest.java
  planfit/src/test/java/com/planfit/server/utils/UserTestUtil.java
Labels: 🎸건우, ✨ Feat

#17 [FEAT] JPA 엔티티 정의 수정(#16)
  planfit/src/main/java/com/planfit/server/common/message/ErrorMessage.java
  planfit/src/main/java/com/planfit/server/common/message/SuccessMessage.java
  planfit/src/main/java/com/planfit/server/domain/Exercise.java
  planfit/src/main/java/com/planfit/server/domain/Routine.java
  planfit/src/main/java/com/planfit/server/domain/Set.java
  planfit/src/main/java/com/planfit/server/dto/response/ExerciseGetResponse.java
Labels: ✨ Feat, 🐶채원

#14 [FEAT] 운동 리스트 순서변경 API 구현 (#13)
  planfit/build.gradle
  planfit/src/main/java/com/planfit/server/common/ApiResponseUtil.java
  planfit/src/main/java/com/planfit/server/common/BaseResponse.java
  planfit/src/main/java/com/planfit/server/common/handler/GlobalExceptionHandler.java
  planfit/src/main/java/com/planfit/server/common/message/ErrorMessage.java
  planfit/src/main/java/com/planfit/server/common/message/SuccessMessage.java
  planfit/src/main/java/com/planfit/server/controller/ExerciseController.java
  planfit/src/main/java/com/planfit/server/domain/Routine.java
  planfit/src/main/java/com/planfit/server/dto/request/ExerciseReorderAllRequest.java
  planfit/src/main/java/com/planfit/server/dto/request/ExerciseReorderRequest.java
  planfit/src/main/java/com/planfit/server/repository/RoutineRepository.java
  planfit/src/main/java/com/planfit/server/service/ExerciseService.java
Labels: ✨ Feat, 🐶채원

#20 [REFACTOR] 서비스 메서드로 수정 #20
  planfit/src/main/java/com/planfit/server/common/handler/GlobalExceptionHandler.java
  planfit/src/main/java/com/planfit/server/common/message/ErrorMessage.java
  planfit/src/main/java/com/planfit/server/common/message/SuccessMessage.java
  planfit/src/main/java/com/planfit/server/domain/Routine.java
  planfit/src/main/java/com/planfit/server/service/ExerciseService.java
Labels: 🐶채원, ♻️ Refactor

#18 [FEAT] 운동 세트 추가 API, 운동 세트 완료 API 구현 (#15)
  planfit/build.gradle
  planfit/src/main/java/com/planfit/server/common/ApiResponseUtil.java
  planfit/src/main/java/com/planfit/server/common/BaseResponse.java
  planfit/src/main/java/com/planfit/server/common/Constant.java
  planfit/src/main/java/com/planfit/server/common/exception/IndexOutOfBoundsException.java
  planfit/src/main/java/com/planfit/server/common/handler/GlobalExceptionHandler.java
  planfit/src/main/java/com/planfit/server/common/message/ErrorMessage.java
  planfit/src/main/java/com/planfit/server/common/message/SuccessMessage.java
  planfit/src/main/java/com/planfit/server/controller/RoutineController.java
  planfit/src/main/java/com/planfit/server/controller/SetController.java
  planfit/src/main/java/com/planfit/server/controller/UserController.java
  planfit/src/main/java/com/planfit/server/domain/Routine.java
  planfit/src/main/java/com/planfit/server/domain/Set.java
  planfit/src/main/java/com/planfit/server/domain/User.java
  planfit/src/main/java/com/planfit/server/dto/request/UserPutRequest.java
  planfit/src/main/java/com/planfit/server/repository/RoutineRepository.java
  planfit/src/main/java/com/planfit/server/repository/SetRepository.java
  planfit/src/main/java/com/planfit/server/service/ExerciseService.java
  planfit/src/main/java/com/planfit/server/service/RoutineService.java
  planfit/src/main/java/com/planfit/server/service/SetService.java
Labels: 🦦성준, ✨ Feat

#22 [ FIX] 순환참조 해결(#21)
  planfit/src/main/java/com/planfit/server/controller/ExerciseController.java
  planfit/src/main/java/com/planfit/server/service/ExerciseService.java
  planfit/src/main/java/com/planfit/server/service/RoutineService.java
Labels: 🛠️ Fix

#24 [CHORE] 컨트롤러 @RequestHeader, @PathVariable 명시(#23)
  planfit/src/main/java/com/planfit/server/controller/ExerciseController.java
  planfit/src/main/java/com/planfit/server/controller/RoutineController.java
  planfit/src/main/java/com/planfit/server/controller/SetController.java
Labels: 🎸건우, 🛠️ Fix
